# Today I learned
print ("Hello Customer, and welcome to our restaurant!")
print ("Here we believe that the customer is always right and so you get to make the dish?")
print ("So let's get started!")
print ("I will ask you a few questions and you will answer them.")
print ("This will help me to make the best dish for you!")
ingrediant1 = input ("What is your favorite meat? ")
ingrediant2 = input ("What is a named for burnt food? ")
ingrediant3 = input ("What is your favorite plant? ")
ingrediant4 = input ("What is your favorite tool? ")
ingrediant5 = input ("What is your favorite way to use this tool? ")
ingrediant6 = input ("What is a word for undercooked meat? ")
ingrediant7 = input ("What is you favorite sauce? ")
print ("So your dish is made of", ingrediant3, "that was", ingrediant2, "with a sauce of", ingrediant7, "and", ingrediant1, "that was", ingrediant6, "made using a", ingrediant4, "by", ingrediant5)
