# Today I Learned
print ("Hello")
YourName = input("What is your name? ")
print ("Hello " + YourName)
YourAge = input("How old are you? ")
print ("You are " + YourAge + " years old")
YourFavouriteFood = input("What is your favourite food? ")
print ("Your favourite food is " + YourFavouriteFood)
YourFavouriteColour = input("What is your favourite colour? ")
print ("Your favourite colour is " + YourFavouriteColour)
YourFavouriteSubject = input("What is your favourite subject? ")
print ("Your favourite subject is " + YourFavouriteSubject)
print (YourName + " is " + YourAge + " years old, their favourite food is " + YourFavouriteFood + ", their favourite colour is " + YourFavouriteColour + " and their favourite subject is " + YourFavouriteSubject)
print ("Type like if you like it or don't like if you don't like it")
Replit = input("Do you like Replit? ")
print ("You " + Replit + " Replit")
print ("Thank you for your time")
